{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b95b8153",
   "metadata": {},
   "outputs": [],
   "source": [
    "import comtypes.client;\n",
    "import os;\n",
    "import sys;\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import math\n",
    "import openpyxl\n",
    "import pyautocad\n",
    "import streamlit as st\n",
    "import sqlite3\n",
    "import io\n",
    "from pyautocad import Autocad, APoint\n",
    "# acad= Autocad()\n",
    "acad = pyautocad.Autocad(create_if_not_exists=True)\n",
    "import xlwings as xw\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "fa305eee",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "already in mm\n",
      "already in mm\n",
      "mm to ft\n",
      "mm to ft\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'1': [0.0, 0.0, 3048.0, 0],\n",
       " '2': [0.0, 0.0, 0.0, 0],\n",
       " '3': [0.0, 5537.20000000001, 3048.0, 0],\n",
       " '4': [0.0, 5537.20000000001, 0.0, 0],\n",
       " '5': [0.0, 9194.80000000001, 3048.0, 0],\n",
       " '6': [0.0, 9194.80000000001, 0.0, 0],\n",
       " '7': [3048.0, 0.0, 3048.0, 0],\n",
       " '8': [3048.0, 0.0, 0.0, 0],\n",
       " '9': [3048.0, 5537.20000000001, 3048.0, 0],\n",
       " '10': [3048.0, 5537.20000000001, 0.0, 0],\n",
       " '11': [3048.0, 9194.80000000001, 3048.0, 0],\n",
       " '12': [3048.0, 9194.80000000001, 0.0, 0],\n",
       " '13': [6096.0, 0.0, 3048.0, 0],\n",
       " '14': [6096.0, 0.0, 0.0, 0],\n",
       " '15': [6096.0, 5537.20000000001, 3048.0, 0],\n",
       " '16': [6096.0, 5537.20000000001, 0.0, 0],\n",
       " '17': [6096.0, 9194.80000000001, 3048.0, 0],\n",
       " '18': [6096.0, 9194.80000000001, 0.0, 0],\n",
       " '19': [9372.6, 0.0, 3048.0, 0],\n",
       " '20': [9372.6, 0.0, 0.0, 0],\n",
       " '21': [9372.6, 5537.20000000001, 3048.0, 0],\n",
       " '22': [9372.6, 5537.20000000001, 0.0, 0],\n",
       " '23': [9372.6, 9194.80000000001, 3048.0, 0],\n",
       " '24': [9372.6, 9194.80000000001, 0.0, 0],\n",
       " '25': [3048.0, 9652.000000000011, 3048.0, 0],\n",
       " '26': [0.0, 9652.000000000011, 3048.0, 0],\n",
       " '27': [6096.0, 9652.000000000011, 3048.0, 0],\n",
       " '28': [9372.6, 9652.000000000011, 3048.0, 0],\n",
       " '29': [-457.2, 5537.20000000001, 3048.0, 0],\n",
       " '30': [-457.2, 0.0, 3048.0, 0],\n",
       " '31': [-457.2, 9194.80000000001, 3048.0, 0],\n",
       " '32': [3048.0, -457.2, 3048.0, 0],\n",
       " '33': [0.0, -457.2, 3048.0, 0],\n",
       " '34': [6096.0, -457.2, 3048.0, 0],\n",
       " '35': [9372.6, -457.2, 3048.0, 0],\n",
       " '36': [9829.800000000001, 5537.20000000001, 3048.0, 0],\n",
       " '37': [9829.800000000001, 0.0, 3048.0, 0],\n",
       " '38': [9829.800000000001, 9194.80000000001, 3048.0, 0],\n",
       " '39': [-457.2, 9652.000000000011, 3048.0, 0],\n",
       " '40': [9829.800000000001, 9652.000000000011, 3048.0, 0],\n",
       " '41': [9829.800000000001, -457.2, 3048.0, 0],\n",
       " '42': [-457.2, -457.2, 3048.0, 0],\n",
       " '43': [0.0, 0.0, 6096.0, 0],\n",
       " '44': [0.0, 5537.20000000001, 6096.0, 0],\n",
       " '45': [0.0, 9194.80000000001, 6096.0, 0],\n",
       " '46': [3048.0, 0.0, 6096.0, 0],\n",
       " '47': [3048.0, 5537.20000000001, 6096.0, 0],\n",
       " '48': [3048.0, 9194.80000000001, 6096.0, 0],\n",
       " '49': [6096.0, 0.0, 6096.0, 0],\n",
       " '50': [6096.0, 5537.20000000001, 6096.0, 0],\n",
       " '51': [6096.0, 9194.80000000001, 6096.0, 0],\n",
       " '52': [9372.6, 0.0, 6096.0, 0],\n",
       " '53': [9372.6, 5537.20000000001, 6096.0, 0],\n",
       " '54': [9372.6, 9194.80000000001, 6096.0, 0],\n",
       " '55': [3048.0, 9652.000000000011, 6096.0, 0],\n",
       " '56': [0.0, 9652.000000000011, 6096.0, 0],\n",
       " '57': [6096.0, 9652.000000000011, 6096.0, 0],\n",
       " '58': [9372.6, 9652.000000000011, 6096.0, 0],\n",
       " '59': [-457.2, 5537.20000000001, 6096.0, 0],\n",
       " '60': [-457.2, 0.0, 6096.0, 0],\n",
       " '61': [-457.2, 9194.80000000001, 6096.0, 0],\n",
       " '62': [3048.0, -457.2, 6096.0, 0],\n",
       " '63': [0.0, -457.2, 6096.0, 0],\n",
       " '64': [6096.0, -457.2, 6096.0, 0],\n",
       " '65': [9372.6, -457.2, 6096.0, 0],\n",
       " '66': [9829.800000000001, 5537.20000000001, 6096.0, 0],\n",
       " '67': [9829.800000000001, 0.0, 6096.0, 0],\n",
       " '68': [9829.800000000001, 9194.80000000001, 6096.0, 0],\n",
       " '69': [-457.2, 9652.000000000011, 6096.0, 0],\n",
       " '70': [9829.800000000001, 9652.000000000011, 6096.0, 0],\n",
       " '71': [9829.800000000001, -457.2, 6096.0, 0],\n",
       " '72': [-457.2, -457.2, 6096.0, 0],\n",
       " '73': [4664.026790832188, 4779.243983584261, 6096.0, 0],\n",
       " '74': [4653.965930516768, 4765.071220172441, 3048.0, 0]}"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "class EtabsConnection:\n",
    "    def __init__(self):\n",
    "        return \n",
    "        #         self.acad = Autocad()\n",
    "    \n",
    "    def connect_to_etabs_2019(self):\n",
    "        \"\"\"\n",
    "        Return Values:\n",
    "        SapModel (type cOAPI pointer)\n",
    "        myETABSObject (type cOAPI pointer)\n",
    "        helper (type cOAPI pointer)\n",
    "        \"\"\"\n",
    "        #create API helper object\n",
    "        helper = comtypes.client.CreateObject('ETABSv1.Helper');\n",
    "        helper = helper.QueryInterface(comtypes.gen.ETABSv1.cHelper);\n",
    "        \n",
    "        #attach to a running instance of ETABS\n",
    "        try:\n",
    "            #get the active ETABS object\n",
    "            myETABSObject = helper.GetObject(\"CSI.ETABS.API.ETABSObject\");\n",
    "        except (OSError, comtypes.COMError):\n",
    "            print(\"No running instance of the program found or failed to attach.\");\n",
    "            sys.exit(-1);\n",
    "        #create SapModel object\n",
    "        SapModel = myETABSObject.SapModel;\n",
    "        return SapModel,myETABSObject,helper;\n",
    "    \n",
    "    # GETS CO-ORDINATES OF ALL THE POINTS FROM ETABS. \n",
    "    def get_coordinates_from_etabs(self,sap_model):\n",
    "        # Get all point names\n",
    "        point_names = sap_model.PointObj.GetNameList()\n",
    "\n",
    "        # Get point coordinates based on unique names\n",
    "        point_coords = {}\n",
    "        for name in point_names[1]:\n",
    "            name = str(name)\n",
    "            coord = sap_model.PointObj.GetCoordCartesian(name)\n",
    "            point_coords[name] = coord\n",
    "\n",
    "        return point_coords\n",
    "\n",
    "    \n",
    "    def convert_to_mm(self, d):\n",
    "        if max(d.values())>1000:\n",
    "            print('already in mm')\n",
    "            return {k: v * 1 for k, v in d.items()}\n",
    "        else:\n",
    "            print('m to mm')\n",
    "            return {k: v * 1000 for k, v in d.items()}\n",
    "        \n",
    "    def convert_to_ft(self, d):\n",
    "        if max(d.values())>1000:\n",
    "            print('mm to ft')\n",
    "            return {k: round(v /304.8,3) for k, v in d.items()}\n",
    "        else:\n",
    "            print('m to ft')\n",
    "            return {k: round(v /0.3048,3) for k, v in d.items()}\n",
    "    \n",
    "    def get_etabs_grids(self, sap_model):\n",
    "        # GET GRID VALUES\n",
    "        get_grids = sap_model.GridSys.GetGridSys_2('G1')\n",
    "\n",
    "        grid_x = dict(zip(get_grids[6],get_grids[8] ))\n",
    "        grid_y = dict(zip(get_grids[7],get_grids[9] ))\n",
    "        grid = [grid_x,grid_y]\n",
    "\n",
    "        grid_x_mm = self.convert_to_mm(grid_x)\n",
    "        grid_y_mm = self.convert_to_mm(grid_y)\n",
    "        grid_mm = [grid_x_mm,grid_y_mm]\n",
    "\n",
    "        grid_x_ft = self.convert_to_ft(grid_x)\n",
    "        grid_y_ft = self.convert_to_ft(grid_y)\n",
    "        grid_ft = [grid_x_ft,grid_y_ft]\n",
    "\n",
    "        return grid,grid_mm,grid_ft\n",
    "    \n",
    "    def get_allframes(self,sap_model):\n",
    "        #RETRIEVES data for all frame objects in the model.\n",
    "         all_frames = sap_model.FrameObj.GetAllFrames()\n",
    "         return all_frames\n",
    "    \n",
    "    def GetAllFrameProperties(self,sap_model):\n",
    "       #Retrieves select data for all frame properties in the model \n",
    "        all_frame_properties = sap_model.PropFrame.GetAllFrameProperties_2()\n",
    "        return all_frame_properties\n",
    "    \n",
    "    \n",
    "\n",
    "connection = EtabsConnection()\n",
    "sap_model, etabs_object, helper = connection.connect_to_etabs_2019()\n",
    "grid_values, grid_mm, grid_ft = connection.get_etabs_grids(sap_model)\n",
    "\n",
    "point_coords = connection.get_coordinates_from_etabs(sap_model)\n",
    "point_coords\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "46dcbf67",
   "metadata": {},
   "outputs": [],
   "source": [
    "all_frames = connection.get_allframes(sap_model)\n",
    "df_frames = pd.DataFrame(all_frames[1:-1])\n",
    "df_frames = df_frames.transpose()\n",
    "# df_frames = df_frames[['0','1','2','3','4','5','6','7','8','9','10']]\n",
    "df_frames = df_frames.iloc[:, :11]\n",
    "col_names = ['U Name','Section','Story','P1','P2','P1x','P1y','P1z','P2x','P2y','P2z']\n",
    "df_frames.columns = col_names\n",
    "\n",
    "all_frame_properties= connection.GetAllFrameProperties(sap_model)\n",
    "df_frame_props = pd.DataFrame(all_frame_properties[1:-1])\n",
    "df_frame_props = df_frame_props.transpose().iloc[:,:4]\n",
    "col_namess = ['Section','ip','Depth','Width']\n",
    "df_frame_props.columns = col_namess\n",
    "df_frame_props = df_frame_props.drop('ip', axis=1)\n",
    "\n",
    "df_frames = pd.merge(df_frames,df_frame_props,on = 'Section')\n",
    "\n",
    "# Define a custom function to extract the first character from the 'Section' column\n",
    "def extract_type(section):\n",
    "    return section.split()[0]\n",
    "\n",
    "# Apply the custom function to the 'Section' column\n",
    "df_frames['Type'] = df_frames['Section'].apply(extract_type)\n",
    "\n",
    "# Map the extracted first character to 'Beam', 'Column', or 'Wall'\n",
    "df_frames['Type'] = df_frames['Type'].map({'B': 'Beam', 'C': 'Column', 'W': 'Wall'})\n",
    "\n",
    "\n",
    "# ADD BLOCK ORIGIN\n",
    "df_frames['Story'].unique()\n",
    "\n",
    "# Get unique values from column 'B'\n",
    "unique_values = sorted(df_frames['Story'].unique())\n",
    "\n",
    "# Create a dictionary with unique values as keys and incremental integers as values\n",
    "n = max(df_frames.iloc[:, [5, 6,8,9]].max())*1.5\n",
    "# n = 100000\n",
    "m = 0\n",
    "value_dict = {unique_values[i]: m+i * n for i in range(len(unique_values))}\n",
    "\n",
    "# value_dict\n",
    "df_frames['Block_origin'] = df_frames['Story'].map(value_dict)\n",
    "\n",
    "\n",
    "# ##################ADD ORIENTATION FUNCTION\n",
    "# Calculate the orientation using arctan2\n",
    "df_frames['orientation'] = [math.degrees(math.atan2(P2y - P1y, P2x - P1x)) for P1x, P1y, P2x, P2y in zip(df_frames['P1x'], df_frames['P1y'], df_frames['P2x'], df_frames['P2y'])]\n",
    "\n",
    "# CHANGE TO MM THE LENGTHS FROM M.\n",
    "# df_frames.iloc[:, 5:13] *= 1000\n",
    "# df_frames['Block_origin'] *= 1000\n",
    "\n",
    "\n",
    "\n",
    "df_frames"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "d08ee1bf",
   "metadata": {},
   "outputs": [],
   "source": [
    "class ExcelConnection:\n",
    "    def __init__(self):\n",
    "        return\n",
    "#         self.file_path = file_path\n",
    "#         self.data = self.load_from_excel()       \n",
    "\n",
    "    def load_from_excel(self,wb_name,ws_name):\n",
    "        # Load the workbook from the running Excel file\n",
    "#         wb_name =  wb_name #\n",
    "       \n",
    "        wb = openpyxl.load_workbook(wb_name,data_only=True)\n",
    "        # Select the foundation_design sheet in the workbook\n",
    "        sheet = wb[ws_name]\n",
    "        # Get the names of the columns from the third row of the sheet\n",
    "        all_columns = [sheet.cell(row=4, column=i+1).value for i in range(sheet.max_column) if sheet.cell(row=4, column=i+1).value is not None]\n",
    "        columns = ['Story', 'Unique Names','Adopted Length', 'Adopted Breadth', 'Type']\n",
    "\n",
    "        # Create a dictionary to store the data for each column\n",
    "        data = {col: [] for col in all_columns}\n",
    "\n",
    "        # Iterate through the rows in the sheet, starting from the fourth row\n",
    "        for row in sheet.iter_rows(min_row=4, max_col=len(all_columns)):\n",
    "            # For each column in the row, add the value to the corresponding list in the data dictionary\n",
    "            for i, cell in enumerate(row):\n",
    "                data[all_columns[i]].append(cell.value)\n",
    "\n",
    "        # Create a Pandas DataFrame from the data dictionary\n",
    "        df = pd.DataFrame(data)\n",
    "        # Get the list of columns to drop (all column names not in `columns_to_keep`)\n",
    "        columns_to_drop = [col for col in df.columns if col not in columns]\n",
    "        # Drop the columns from the DataFrame\n",
    "        df.drop(columns_to_drop, axis=1, inplace=True)\n",
    "\n",
    "        # Drop the first row of the DataFrame\n",
    "        df.drop(index=df.index[:2],inplace=True)\n",
    "        df.reset_index()\n",
    "        # Convert to mm from m. \n",
    "#         print(df)\n",
    "        df['Adopted Length'] = df['Adopted Length']*1000\n",
    "        df['Adopted Breadth'] = df['Adopted Breadth']*1000\n",
    "\n",
    "        df_copy = df.copy()\n",
    "        # sort values in ascending order of col2 and col3\n",
    "        df_copy = df_copy.sort_values(by=['Adopted Length', 'Adopted Breadth'])\n",
    "        df_copy['combined'] = df_copy[['Adopted Length', 'Adopted Breadth']].apply(lambda x: ' '.join(x.astype(str)), axis=1)\n",
    "        df_unique = df_copy.drop_duplicates(subset='combined')\n",
    "        df_unique = df_unique.reset_index(drop=True)\n",
    "        df_unique['assigned_value'] = [\"F\" + str(i + 1) for i in range(len(df_unique))]\n",
    "        df_mapping = dict(zip(df_unique['combined'], df_unique['assigned_value']))\n",
    "        df['Name'] = df_copy['combined'].map(df_mapping)\n",
    "\n",
    "        return df\n",
    "\n",
    "    # READ  EXCEL TABLE\n",
    "    def excel_table():\n",
    "        st.write(\"CHECK DATA FROM EXCEL\")    \n",
    "        # Get a reference to the active Excel application\n",
    "        app = xw.apps.active\n",
    "        # Get a reference to the active worksheet\n",
    "        sheet = app.books.active.sheets.active\n",
    "        # Get the selected range of cells\n",
    "        selection = app.selection\n",
    "\n",
    "        if selection:\n",
    "            values = selection.options(ndim=2).value\n",
    "        else:\n",
    "            # Get all values in the used range of the worksheet\n",
    "            values = sheet.used_range.options(ndim=2).value\n",
    "        \n",
    "        values = np.array(values)\n",
    "        # print(values)\n",
    "        return values\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "65aa0736",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\nisha\\anaconda3\\lib\\site-packages\\openpyxl\\reader\\drawings.py:29: UserWarning: DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.\n",
      "  warn(\"DrawingML support is incomplete and limited to charts and images only. Shapes and drawings will be lost.\")\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Story</th>\n",
       "      <th>Unique Names</th>\n",
       "      <th>Adopted Length</th>\n",
       "      <th>Adopted Breadth</th>\n",
       "      <th>Name</th>\n",
       "      <th>x</th>\n",
       "      <th>y</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Ground</td>\n",
       "      <td>2</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>F1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Ground</td>\n",
       "      <td>4</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>F1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>5537.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Ground</td>\n",
       "      <td>6</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>F1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>9194.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Ground</td>\n",
       "      <td>8</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>F1</td>\n",
       "      <td>3048.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Ground</td>\n",
       "      <td>10</td>\n",
       "      <td>1650.0</td>\n",
       "      <td>1650.0</td>\n",
       "      <td>F2</td>\n",
       "      <td>3048.0</td>\n",
       "      <td>5537.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Ground</td>\n",
       "      <td>12</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>F1</td>\n",
       "      <td>3048.0</td>\n",
       "      <td>9194.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Ground</td>\n",
       "      <td>14</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>F1</td>\n",
       "      <td>6096.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Ground</td>\n",
       "      <td>16</td>\n",
       "      <td>1650.0</td>\n",
       "      <td>1650.0</td>\n",
       "      <td>F2</td>\n",
       "      <td>6096.0</td>\n",
       "      <td>5537.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Ground</td>\n",
       "      <td>18</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>F1</td>\n",
       "      <td>6096.0</td>\n",
       "      <td>9194.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Ground</td>\n",
       "      <td>20</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>F1</td>\n",
       "      <td>9372.6</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Ground</td>\n",
       "      <td>22</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>F1</td>\n",
       "      <td>9372.6</td>\n",
       "      <td>5537.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Ground</td>\n",
       "      <td>24</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>1500.0</td>\n",
       "      <td>F1</td>\n",
       "      <td>9372.6</td>\n",
       "      <td>9194.8</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     Story Unique Names Adopted Length Adopted Breadth Name       x       y\n",
       "2   Ground            2         1500.0          1500.0   F1     0.0     0.0\n",
       "3   Ground            4         1500.0          1500.0   F1     0.0  5537.2\n",
       "4   Ground            6         1500.0          1500.0   F1     0.0  9194.8\n",
       "5   Ground            8         1500.0          1500.0   F1  3048.0     0.0\n",
       "6   Ground           10         1650.0          1650.0   F2  3048.0  5537.2\n",
       "7   Ground           12         1500.0          1500.0   F1  3048.0  9194.8\n",
       "8   Ground           14         1500.0          1500.0   F1  6096.0     0.0\n",
       "9   Ground           16         1650.0          1650.0   F2  6096.0  5537.2\n",
       "10  Ground           18         1500.0          1500.0   F1  6096.0  9194.8\n",
       "11  Ground           20         1500.0          1500.0   F1  9372.6     0.0\n",
       "12  Ground           22         1500.0          1500.0   F1  9372.6  5537.2\n",
       "13  Ground           24         1500.0          1500.0   F1  9372.6  9194.8"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "excel_connection = ExcelConnection()\n",
    "wb_name = 'Darchula_footing_api.xlsx'\n",
    "ws_name = 'Foundation_Design'\n",
    "df = ExcelConnection().load_from_excel(wb_name,ws_name)\n",
    "df\n",
    "df = df.dropna()\n",
    "\n",
    "def find_xy(label):\n",
    "    return point_coords[str(label)][0], point_coords[str(label)][1]\n",
    "\n",
    "df['x'], df['y'] = zip(*df['Unique Names'].apply(find_xy))\n",
    "\n",
    "# df['x'] = 1000*df['x']\n",
    "# df['y'] = 1000*df['y']\n",
    "\n",
    "\n",
    "df\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "dd88b181",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['F1', 'F2'], dtype=object)"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# df['Name'].unique().sort_values(by=['Name'])\n",
    "df_names = df['Name'].unique()\n",
    "np.sort(df_names)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "6845a0ad",
   "metadata": {},
   "outputs": [],
   "source": [
    "class AutocadConnection:\n",
    "    def __init__(self):\n",
    "     \n",
    "        \n",
    "        return\n",
    "#         self.file_path = file_path\n",
    "#         self.data = self.load_from_excel()       \n",
    "\n",
    "    # DRAWS RECTANGLES AND NAMES I.E. FOUNDATIONS INTO THE OPEN AUTOCAD MODEL IN METERS\n",
    "    def draw_rect(self, width,height,origin_x,origin_y,Name,dimd,txt_ht,col_size,dim_check,name_check):\n",
    "               \n",
    "        p1 = APoint(origin_x+width/2, origin_y+height/2)\n",
    "        p2 = APoint(origin_x+width/2, origin_y-height/2)\n",
    "        p3 = APoint(origin_x-width/2, origin_y-height/2)\n",
    "        p4 = APoint(origin_x-width/2, origin_y+height/2)\n",
    "\n",
    "\n",
    "        line1 = acad.model.AddLine(p1, p2)\n",
    "        line2 = acad.model.AddLine(p2, p3)\n",
    "        line3 = acad.model.AddLine(p3, p4)\n",
    "        line4 = acad.model.AddLine(p4, p1)\n",
    "        \n",
    "        line1.layer = 'line_0.25'\n",
    "        line2.layer = 'line_0.25'\n",
    "        line3.layer = 'line_0.25'\n",
    "        line4.layer = 'line_0.25'\n",
    "\n",
    "        if name_check =='yes':\n",
    "            t1 = acad.model.AddText(Name, APoint(origin_x+col_size, origin_y+col_size),txt_ht)\n",
    "            t1.layer = 'Text'\n",
    "        \n",
    "        if dim_check =='yes':\n",
    "            # Add dimensions to the two adjacent lines\n",
    "            pd1 = APoint(origin_x+width/2+dimd, origin_y+height/2)\n",
    "\n",
    "            pd2 = APoint(origin_x-width/2, origin_y-height/2-dimd)\n",
    "\n",
    "\n",
    "            dim1= acad.model.AddDimAligned(p1, p2, pd1)\n",
    "            dim2 = acad.model.AddDimAligned(p2, p3, pd2)\n",
    "            dim1.layer = 'Dimension'\n",
    "            dim2.layer = 'Dimension'\n",
    "\n",
    "    # DRAWS RECTANGLES AND NAMES I.E. FOUNDATIONS INTO THE OPEN AUTOCAD MODEL IN METERS\n",
    "    def draw_beams(self, width,origin_x,origin_y,end_x,end_y,Name,txt_ht,orientation):       \n",
    "        if orientation == 0:\n",
    "            p1 = APoint(origin_x, origin_y+width/2)\n",
    "            p2 = APoint(end_x, end_y+width/2)\n",
    "            p3 = APoint(origin_x, origin_y-width/2)\n",
    "            p4 = APoint(end_x, end_y-width/2)\n",
    "            t1 = acad.model.AddText(Name, APoint((origin_x+end_x)/2, origin_y),txt_ht)\n",
    "            t1.Alignment = 4\n",
    "            t1.TextAlignmentPoint = APoint((origin_x+end_x)/2, origin_y+width/2+25+txt_ht)\n",
    "            line1 = acad.model.AddLine(p1, p2)\n",
    "            line2 = acad.model.AddLine(p3, p4) \n",
    "\n",
    "        if orientation == 90:\n",
    "            p1 = APoint(origin_x+width/2, origin_y)\n",
    "            p2 = APoint(end_x+width/2, end_y)\n",
    "            p3 = APoint(origin_x-width/2, origin_y)\n",
    "            p4 = APoint(end_x-width/2, end_y)\n",
    "            t1 = acad.model.AddText(Name, APoint(origin_x, (origin_y+end_y)/2),txt_ht)           \n",
    "            t1.Alignment = 4\n",
    "            t1.TextAlignmentPoint = APoint(origin_x-width/2-25-txt_ht, (origin_y+end_y)/2)\n",
    "            t1.rotation = math.pi/2\n",
    "            line1 = acad.model.AddLine(p1, p2)\n",
    "            line2 = acad.model.AddLine(p3, p4)          \n",
    "\n",
    "        line1.layer = 'line_0.25'\n",
    "        line2.layer = 'line_0.25'\n",
    "        t1.layer = 'Text'\n",
    "    \n",
    "#     ADD BLOCK NAMES TO DRAWING\n",
    "    def add_block_name(self,Block_origin,offset,txt_ht,block_name,algt):\n",
    "        t1 = acad.model.AddText(block_name, APoint(Block_origin, 0-offset),txt_ht)\n",
    "        t1.Alignment = algt\n",
    "        t1.TextAlignmentPoint = APoint(Block_origin, 0-offset) \n",
    "        \n",
    "    # FUNCTION TO DRAW GRID LINES IN AUTOCAD.\n",
    "    def draw_grid_lines(self, grid, offset, txt_ht,Block_origin):\n",
    "    \n",
    "        # Get the grid names and coordinates\n",
    "        grid_names_x = list(grid[0].keys())\n",
    "        grid_names_y = list(grid[1].keys())\n",
    "        x_coordinates = list(grid[0].values())+Block_origin\n",
    "        y_coordinates = list(grid[1].values())\n",
    "\n",
    "        # Get the maximum x and y values\n",
    "        max_x = max(x_coordinates)\n",
    "        max_y = max(y_coordinates)\n",
    "\n",
    "        # Define the origin of the grid\n",
    "        origin_x = min(x_coordinates) - offset\n",
    "        origin_y = min(y_coordinates) - offset\n",
    "\n",
    "        # Loop through each x coordinate\n",
    "        for i in range(len(x_coordinates)):\n",
    "            # Create the points for the grid line\n",
    "            p1 = APoint(x_coordinates[i] , origin_y)\n",
    "            p2 = APoint(x_coordinates[i] , max_y+offset)\n",
    "\n",
    "            # Add the line between the two points\n",
    "            line1 = acad.model.AddLine(p1, p2)\n",
    "            line1.layer = 'Grid'\n",
    "\n",
    "            # Add the dimension for the grid line\n",
    "            if i !=len(x_coordinates)-1:\n",
    "                pd = APoint(x_coordinates[i+1] , max_y+offset)\n",
    "                dim1=acad.model.AddDimAligned(APoint(p2.x,p2.y-txt_ht), APoint(pd.x, pd.y - txt_ht),APoint(pd.x, pd.y - txt_ht))\n",
    "                dim1.layer = 'Dimension'\n",
    "\n",
    "            # Add the name of the grid line at the end of the line\n",
    "            acad.model.Addcircle(APoint(p2.x, p2.y + txt_ht), txt_ht)\n",
    "            t1= acad.model.AddText(grid_names_x[i], APoint(p2.x, p2.y + txt_ht), txt_ht)\n",
    "            t1.Alignment = 4\n",
    "            t1.TextAlignmentPoint = APoint(p2.x, p2.y + txt_ht)\n",
    "            t1.layer = 'Text'\n",
    "\n",
    "        # Loop through each y coordinate\n",
    "        for i in range(len(y_coordinates)):\n",
    "            # Create the points for the grid line\n",
    "            p1 = APoint(origin_x, y_coordinates[i] )\n",
    "            p2 = APoint(max_x+offset, y_coordinates[i])\n",
    "\n",
    "            # Add the line between the two points\n",
    "            line1 = acad.model.AddLine(p1, p2)\n",
    "            line1.layer = 'Grid'\n",
    "\n",
    "        # Add the dimension for the grid line\n",
    "            if i !=len(y_coordinates)-1:\n",
    "                pd = APoint(origin_x, y_coordinates[i+1] )\n",
    "                dim1 = acad.model.AddDimAligned(APoint(p1.x+txt_ht,p1.y), APoint(pd.x+txt_ht, pd.y ),APoint(pd.x+txt_ht, pd.y ))\n",
    "                dim1.layer = 'Dimension'\n",
    "\n",
    "            # Add the name of the grid line at the end of the line\n",
    "            cir1 = acad.model.Addcircle(APoint(p1.x - txt_ht, p1.y), txt_ht)\n",
    "            cir1.layer = 'Grid'\n",
    "            \n",
    "            t2 =acad.model.AddText(grid_names_y[i], APoint(p1.x - txt_ht, p1.y), txt_ht)\n",
    "            t2.Alignment = 4\n",
    "            t2.TextAlignmentPoint = APoint(p1.x - txt_ht, p1.y)\n",
    "            t2.layer = 'Text'\n",
    "\n",
    "    def excel_autocad_table(self,table_from_excel):\n",
    "        st.subheader(\"Draw Selected Table from excel to Autocad\")\n",
    "        # if st.button(\"Import Data From Excel\"):\n",
    "        # table_from_excel = excel_table()\n",
    "        st.write(table_from_excel)\n",
    "\n",
    "        col1,col2,col3,col4 = st.columns(4)\n",
    "        with col1:\n",
    "            row_ht = st.number_input(\"Insert Ht. of Rows\",value = 50)\n",
    "        with col2:\n",
    "            col_ht =  st.number_input(\"Insert Ht. of Columns\",value =200)\n",
    "        with col3:\n",
    "            table_header_txt_ht = st.number_input(\"Insert Ht. of Rows\",value = 30)  \n",
    "        with col4:\n",
    "            table_content_txt_ht =  st.number_input(\"Insert Ht. of Columns\",value =20)  \n",
    "        table_header = st.text_input(\"Insert Table Header\",value = table_from_excel[0][0])\n",
    "\n",
    "        if st.button(\"Draw Table\"):\n",
    "            # Create the table\n",
    "            table = acad.model.AddTable(APoint(0,0,0),table_from_excel.shape[0],table_from_excel.shape[1],row_ht,col_ht)\n",
    "\n",
    "            # iterate over the array and set the text and alignment of each cell in the table\n",
    "            for i in range(table_from_excel.shape[0]):\n",
    "                for j in range(table_from_excel.shape[1]):\n",
    "                    \n",
    "                    cell_text = str(table_from_excel[i][j]) # convert the element to a string\n",
    "                    if cell_text != \"None\":\n",
    "                        table.SetText(i, j, cell_text) # set the text of the cell\n",
    "                        table.SetCellAlignment(i, j, 5) # set the alignment of the cell\n",
    "\n",
    "            table.SetText(0,0,table_header)\n",
    "\n",
    "            table.SetTextHeight(5,table_content_txt_ht)\n",
    "            table.SetTextHeight(2,table_header_txt_ht)\n",
    "            # Update the table with the new text height\n",
    "            table.Update() \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "0ff1c586",
   "metadata": {},
   "outputs": [],
   "source": [
    "acad = Autocad()\n",
    "acad.doc.Layers.Add('line_0.25')\n",
    "acad.doc.Layers.Add('Grid')\n",
    "acad.doc.Layers.Add('Text')\n",
    "acad.doc.Layers.Add('Dimension') \n",
    "autocad_connection = AutocadConnection()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "0d1298b7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Story1\n",
      "Story2\n"
     ]
    }
   ],
   "source": [
    "#############  DRAW BEAMS ###########\n",
    "# Define a custom function to be applied to the dataframe to draw beams\n",
    "def call_draw_beams(row):   \n",
    "    if row['Type'] == 'Beam':\n",
    "        AutocadConnection().draw_beams(row['Width'],row['Block_origin'] +row['P1x'],row['P1y'],row['Block_origin'] +row['P2x'],row['P2y'],row['Section'],200,row['orientation'])\n",
    "        \n",
    "# Use the apply method to apply the custom function to each row\n",
    "df_frames['D'] = df_frames.apply(call_draw_beams, axis=1)\n",
    "\n",
    "for item in df_frames['Story'].unique():\n",
    "    print (item)\n",
    "    Block_origin = df_frames.loc[df_frames['Story'] == item,'Block_origin'].values[0]\n",
    "    AutocadConnection().add_block_name(Block_origin,4000,500,'Beam Layout Plan at  ' + str(item),5)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "2639dfcd",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# ######## FUNCTION TO DRAW COLUMNS IN AUTOCAD ##########\n",
    "\n",
    "# Define a custom function to be applied to the dataframe\n",
    "def call_draw_cols(row):   \n",
    "    if row['Type'] == 'Column':\n",
    "        AutocadConnection().draw_rect(float( row['Depth']),float( row['Width']), float(row['Block_origin'] + row['P1x']), float(row['P1y']),row['Section'],500,200,500*0.6,'no','no')\n",
    "\n",
    "# Use the apply method to apply the custom function to each row\n",
    "df_frames['D'] = df_frames.apply(call_draw_cols, axis=1)\n",
    "\n",
    "\n",
    "# DRAW MULTIPLE GRIDS AS PER REUIREMENT OF COLUNN GRIDS\n",
    "for item in df_frames['Story'].unique():\n",
    "    Block_origin = df_frames.loc[df_frames['Story'] == item,'Block_origin'].values[0]\n",
    "    AutocadConnection().draw_grid_lines(grid_mm,2000,300,Block_origin)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "011a33d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# DRAW IN M\n",
    "# DRAW  GRID AS PER THE BLOCK ORIGIN\n",
    "AutocadConnection().draw_grid_lines(grid_mm,2000,300,[])\n",
    "\n",
    "## FUNCTION TO ADD NAME OF THE BLOCK\n",
    "AutocadConnection().add_block_name(0,4000,500,'FOUNDATION LAYOUT PLAN',5)\n",
    "\n",
    "\n",
    "## FUNCTION TO CALL THE DRAW RECTANGLE FUNCTION FROM EACH ROW OF PANDA DATAFRAME. \n",
    "for index, row in df.iterrows():\n",
    "   AutocadConnection().draw_rect(float(row['Adopted Length']),float( row['Adopted Breadth']), float(row['x']), float(row['y']),row['Name'],500,200,500*0.6,'yes','yes')\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "id": "57fac267",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pyautocad\n",
    "\n",
    "# Connect to a running instance of AutoCAD\n",
    "acad = pyautocad.Autocad()\n",
    "\n",
    "doc = acad.ActiveDocument\n",
    "# ms = doc.ModelSpace\n",
    "\n",
    "\n",
    "# Define table properties\n",
    "table_width = 100\n",
    "table_height = 50\n",
    "table_rows = 3\n",
    "table_cols = 5\n",
    "num_rows = 4\n",
    "num_cols = 6\n",
    "\n",
    "# Create the table\n",
    "table = acad.model.AddTable(APoint(0,0,0),num_rows,num_cols,50,200)\n",
    "\n",
    "# Populate the table with data\n",
    "\n",
    "table.SetText(0,0,\"Foundation Details\")\n",
    "for i in range(num_rows):\n",
    "    \n",
    "    for j in range(num_cols):\n",
    "        cell_text = f\"Row {i+1}, Col {j+1}\"\n",
    "        table.SetText(i, j, cell_text)\n",
    "        table.SetCellAlignment(i,j,5)\n",
    "\n",
    "table.SetText(0,0,\"Foundation Details\")\n",
    "# table_style = doc.AcadTableStyle.Item(table.AcadTableStyle)\n",
    "\n",
    "# Set the text height of the table\n",
    "# table_style.SetTextHeight(50)\n",
    "# table.SetTextHeight2(2,2,\"Nishan\",50)\n",
    "table.SetTextHeight(5,20)\n",
    "table.SetTextHeight(2,30)\n",
    "\n",
    "# Update the table with the new text height\n",
    "table.Update()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "id": "27a1d5a9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[' ISOLATED FOOTING DETAILS', None, None, None, None, None, None, None, None, None, None], ['Foundation', 'Column Position', 'Length', 'Breadth', 'Length', 'Breadth', 'd', 'D', 'a', 'Rebar Dia', 'Spacing'], [None, None, 'm', 'm', 'ft', 'ft', 'mm', 'mm', 'mm', 'mm', 'mm'], ['F1', None, 1.5, 1.5, 7.0, 7.0, 200.0, 500.0, 350.0, 12.0, 150.0], ['F2', None, 2.0, 2.0, None, None, 200.0, 500.0, 350.0, 12.0, 150.0], ['F3', None, 2.25, 2.25, None, None, 200.0, 500.0, 350.0, 12.0, 150.0], ['F4', None, 2.5, 2.5, None, None, 200.0, 600.0, 400.0, 12.0, 125.0], ['F5', None, 2.75, 2.75, None, None, 250.0, 600.0, 400.0, 12.0, 125.0], ['F6', None, 3.0, 3.0, None, None, 300.0, 650.0, 425.0, 12.0, 100.0], ['F7', None, 3.25, 3.25, None, None, 300.0, 650.0, 425.0, 12.0, 100.0]]\n"
     ]
    }
   ],
   "source": [
    "import xlwings as xw\n",
    "\n",
    "# Get a reference to the active Excel application\n",
    "app = xw.apps.active\n",
    "\n",
    "# Get a reference to the active worksheet\n",
    "sheet = app.books.active.sheets.active\n",
    "\n",
    "# Get the selected range of cells\n",
    "selection = app.selection\n",
    "if selection:\n",
    "    values = selection.options(ndim=2).value\n",
    "    \n",
    "else:\n",
    "    # Get all values in the used range of the worksheet\n",
    "    values = sheet.used_range.options(ndim=2).value\n",
    "\n",
    "print(values)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e3ee7d6a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
